apiVersion: v1
kind: Secret
metadata:
  name: kedartemis
  namespace: keda-demo
  labels:
    app: camel-amqp-quarkus
type: Opaque
data:
  artemis-password: "YXJ0ZW1pcw=="
  artemis-username: "YXJ0ZW1pcw=="
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-kedartemis
  namespace: keda-demo
spec:
  secretTargetRef:
    - parameter: username
      name: kedartemis
      key: artemis-username
    - parameter: password
      name: kedartemis
      key: artemis-password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: camel-amqp-quarkus-scaler
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: camel-amqp-quarkus
  pollingInterval: 30
  cooldownPeriod:  30  # Default: 300 seconds
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
    - type: artemis-queue
      metadata:
        managementEndpoint: "artemis.keda-demo:8161"
        brokerName: "keda-demo-broker"
        username: 'QUARKUS_QPID_JMS_USERNAME'
        password: 'QUARKUS_QPID_JMS_PASSWORD'
        queueName: "ALEX.HONKING"
        brokerAddress: "ALEX.HONKING"
        queueLength: '10'
        queueLength: '10'
      authenticationRef:
        name: trigger-auth-kedartemis